# Generated by Django 4.1 on 2022-09-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_user_remove_url_id_remove_url_uuid_url_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_premium',
            field=models.BooleanField(default=False),
        ),
    ]
