# Generated by Django 4.1 on 2022-09-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_user_has_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_id',
            field=models.EmailField(blank=True, max_length=128),
        ),
    ]
